- NEWS.md
- src/delimited_index.cc
- src/delimited_index_connection.cc
This PR fixes an overflow during indexing. This causes the error below when reading a file with more than 2B entries.
```r
m <- data.frame(x1 = rep(0, 1e9), x2 = rep(1, 1e9), x3 = rep(2, 1e9))
f <- tempfile()
vroom::vroom_write(m, f)
df <- vroom::vroom(f)
#> Error in vroom_(file, delim = delim, col_names = col_names, col_types = col_types,  : 
Failure to retrieve index 184,467,440,724,145,845 / 6,148,914,690,804,861,440 
```
I am able to reproduce this on MacOS with clang 6 and Ubuntu with gcc 7.4. In both cases, the literal `0` starting value for `std::accumulate` is interpreted as `int` rather than `size_t`.
> Fix overflow during indexing for data with more than 2B entries

- DESCRIPTION
Enables interpackage linking on pkgdown sites (e.g. `vroom::vroom()` in multidplyr docs will go to vroom's pkgdown function reference instead of rdrr.io)
> Add pkgdown site as reference URL

- NEWS.md
- src/vroom_dbl.cc
- src/vroom_dbl.h
- tests/testthat/test-dbl.R
Fixed by providing `decimalMark` to `bsd_strtod` instead of using hard-coded `'.'`.
> Correctly read double values with comma as decimal separator #313

- DESCRIPTION
- NEWS.md
- R/locale.R
- R/zzz.R
- src/DateTime.h
This PR replaces the usage of clock with [zones](https://github.com/r-lib/zones).
zones is a lightweight way to expose the date library's header API, along with 3 callables for working with time zones. As of [this PR](https://github.com/r-lib/clock/pull/222), clock now uses zones as well, rather than embedding date directly.
I am hopeful that compilation times for vroom should be much faster now. For example, on vroom's Ubuntu r-devel check I see:
> ✔ Built zones 0.0.0.9000 (15.2s)
VS this with clock
> ✔ Built clock 0.2.0 (2m 38.3s)
At the advice of other r-lib co-workers on Slack, the callables now require a `std::string& error` argument. If this is not empty after calling a zones callable, that is the signal that an error has occurred when either loading the time zone or looking up the …
> Replace usage of clock with tzdb

- R/path.R
- R/vroom.R
- R/vroom_fwf.R
- R/vroom_lines.R
We check this dynamically by trying to encode a newline. If it is the
same value as ASCII it will be compatible, so no re-encoding is needed.
On my macOS machine `iconvlist()` knows of 419 encodings, and only the ones below are not byte compatible with ASCII newlines.
I think should work pretty well in practice then, we should only have to re-encode a small number of encodings, though UTF-16 and UCS-2 are pretty common unfortunately.
``` r
is_ascii_compatible <- function(encoding) {
identical(iconv(list(charToRaw("\n")), from = "ASCII", to = encoding, toRaw = TRUE)[[1]], charToRaw("\n"))
}
x <- purrr::map_lgl(purrr::set_names(iconvlist()), is_ascii_compatible)
x[!x]
#>          CSUCS4       CSUNICODE     CSUNICODE11 ISO-10646-UCS-2 ISO-10646-UCS-4 
#>           FALSE           FALSE …
```
> Only re-encode ASCII incompatible encodings

- tests/testthat/test-problems.R
- tests/testthat/test-vroom.R
We are planning a breaking change to the condition expectations in testthat release (see NEWS item in https://github.com/r-lib/testthat/pull/1401). This PR implements a preventive fix that works with and without the breaking change.
There is no hurry to get this fix on CRAN since we are skipping one released version of testthat before going through with the change.
> Fix condition expectations in prevision of testthat breaking change

- R/utils.R
I think this is the simplest fix - the R CMD check of method/generic consistency isn't a problem because the method is registered dynamically. If you think its important, I could do the comparison once, on load, but it doesn't seem that important to me.
> Hack return value of compare_proxy

- NEWS.md
- src/utils.h
i.e. fixes:
```cpp
/usr/local/bin/../include/c++/v1/__utility/pair.h:192:52: runtime error: load of value 128, which is not a valid value for type 'bool'
#0 0x7f1daea6b953 in std::__1::pair<bool, bool>::pair<bool, bool&, false>(bool&&, bool&) /usr/local/bin/../include/c++/v1/__utility/pair.h:192:52
#1 0x7f1daea6b3f9 in vroom::is_blank_or_comment_line(char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) /data/gannet/ripley/R/packages/tests-clang-SAN/vroom/src/./utils.h:68:12
```
The first commit is the minimal change required to fix this. I just avoided creating `has_comment` entirely, since it didn't seem to have anything to do with the first half of the if statement.
The second commit slightly refactors the function …
> Avoid an uninitialized `bool` for the CRAN UBSAN check

- NEWS.md
- R/vroom_write.R
Closes #389 
The analysis in this comment was correct https://github.com/r-lib/vroom/issues/389#issuecomment-983667565, the `output_column()` method for POSIXct was creating another character ALTREP vector _after_ `vroom_convert()` was called.
I didn't add a test, because this is hard to test for, but I confirmed that the reprex here no longer errors https://github.com/r-lib/vroom/issues/389#issuecomment-983691057
---
POSIXct isn't necessarily the only type where this could happen.
`output_column.POSIXt()` calls `format()`, and what is happening in `format()` is:
* There is some C code that converts POSIXct -> character and returns a non-altrep character vector called `y`
* At the R level, there is some code that adds names onto `y`
* `names<-` at the C level will create an “ALTREP …
> Fix recursive gc error that could occur with POSIXct columns

- NEWS.md
- R/vroom_write.R
- src/vroom_write.cc
- tests/testthat/test-vroom_write.R
Closes #425 
`vroom_format()` and `readr::format_csv()` return the empty string now.
> `vroom_format()` handles empty data frames

- .github/workflows/R-CMD-check.yaml
- NEWS.md
- R/path.R
- R/vroom.R
- R/vroom_fwf.R
- R/vroom_lines.R
- tests/testthat/test-path.R
Closes #394, closes #402, closes #403 (previous explorations)
There's a bit more going on here than we originally thought and the solution isn't quite as simple as "UTF-8 everywhere" (but it's close).
First, the file from the original issue (https://github.com/tidyverse/readr/issues/1345) has a path containing non-ascii characters, but what's easier to miss is that the file also lacks a trailing newline. The failure cascade looks like this:
[`has_trailing_newline()`](https://github.com/tidyverse/vroom/blob/829ba962b8f263e0833d8905376a7cb05bea9a70/src/vroom.cc#L95-L110) implicitly expects that the path is in the native encoding and, if it's not, can potentially fail to find an existing file. When  that happens, it unconditionally reports `TRUE` (yes, there is a trailing new line), which is …
> Better handling of non-ascii filepaths

- README.Rmd
- README.md
Having only 30% is making it look way to small on GitHub, and it seems
to still look right on the pkgdown site as well without an explicit
width.
> Remove the width from the taylor gif

- .github/workflows/R-CMD-check.yaml
- .github/workflows/debug.yaml
This is about aligning to GitHub's posture towards Ubuntu versions.
In GHA, we're starting to see this for vroom:
> The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002
We deliberately use an "old-ish" Ubuntu version for `R-CMD-check` workflow, but I think it's time to roll forward.
> Roll the ubuntu version

- NEWS.md
- R/vroom_write.R
- tests/testthat/test-vroom_write.R
Fixes tidyverse/readr#1408
Previously, if `vroom_write()` was supplied an empty data frame, vroom created an empty file without checking the value of `append`. But this meant data from the file could be deleted such as in this case.
``` 
library(vroom)
tf <- withr::local_tempfile()
data <- tibble::tibble(a = "1", b = "2", c = "3")
vroom_write(data, file = tf)
vroom(tf, show_col_types = FALSE)
#> # A tibble: 1 × 3
#>       a     b     c
#>   <dbl> <dbl> <dbl>
#> 1     1     2     3
vroom_write(data.frame(), file = tf, append = TRUE)
vroom(tf, show_col_types = FALSE)
#> # A tibble: 0 × 0
```
<sup>Created on 2022-07-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>
> Don’t overwrite existing file if appending an empty data frame

- tests/testthat/test-problems.R
Fixes #445 
This might be a bit redundant/circular, but I'm going to relink @DavisVaughan issue post about this because I found it really useful for refreshing my memory on the problem
https://github.com/r-lib/cpp11/issues/274
> Update test for `unwind::protect` error in `vroom_errors::warn_for_errors()`

- NEWS.md
- R/col_types.R
- R/vroom.R
- man/vroom.Rd
- tests/testthat/test-select.R
- vignettes/vroom.Rmd
Fixes #416, Fixes #455 
The `id` column now does not have to be included in `col_select` (but still can be).
``` r
out1 <- glue::glue("a,b,c,d
1,2,3,4")
out2 <- glue::glue("a,b,c,d
5,6,7,8")
tf1 <- withr::local_tempfile(fileext = ".csv", lines = out1)
tf2 <- withr::local_tempfile(fileext = ".csv", lines = out2)
vroom(
c(tf1, tf2),
id = "source",
col_select = c("a", "c"),
show_col_types = FALSE
)
#> # A tibble: 2 × 3
#>   source                  a     c
#>   <chr>               <dbl> <dbl>
#> 1 /var/folders/4g/9j…     1     3
#> 2 /var/folders/4g/9j…     5     7
vroom(
c(tf1, tf2),
id = "source",
col_select = c("a", "c", "source"),
show_col_types = FALSE
)
#> # A tibble: 2 × 3
#>       a     c source             
#>   <dbl> <dbl> <chr>              
#> 1     1     3 /var/folders/4g/9j…
#> …
```
> Include `id` column in `col_select` by default

- R/vroom.R
- man/gen_tbl.Rd
- man/vroom.Rd
- man/vroom_lines.Rd
Closes #461
Moving over docs from readr to vroom so that the primary docs live here which we think makes more sense.
Note: this would also fix part of https://github.com/tidyverse/readr/issues/1421 (removing mention of `list()` with `col_select`) but we'd still need to add examples of `col_select()`
> Don't inherit docs from readr

- DESCRIPTION
- R/cpp11.R
- R/path.R
- src/cpp11.cpp
- tests/testthat/_snaps/path.md
- tests/testthat/test-path.R
`details` will now be formatted with cli which causes this message to be width-wrapped, losing the newlines. With a future of cli, this sort of pattern will be made easier with "raw bullets".
> Pass cli bullets to lifecycle

- src/grisu3.c
- src/vroom_write.cc
In `vroom_write.cc` we know the size of the output buffer (defined in the line above) so we use that to limit the size.
The two cases in `grisu3.c` we don't know the size of the buffer, so we limit to the input size+1. (+1 for the null terminator).
> Replace sprintf() with snprintf()

- src/vroom_write.cc
https://releases.llvm.org/5.0.1/tools/clang/tools/extra/docs/clang-tidy/checks/readability-container-size-empty.html
> Use .empty() method

- R/col_types.R
- tests/testthat/test-vroom.R
Fixes #453
In older versions of R, like 3.6.3, there is an error when reading an empty date or date-time column with skip = 1.
```
vroom::vroom(I('date\n'), col_names = 'date', col_types = 'D', skip = 1L)
Error in as.Date.numeric(double()) : 'origin' must be supplied
Calls: <Anonymous> ... collector_value.collector_date -> as.Date -> as.Date.numeric
```
```
vroom::vroom(I('dt\n'), col_names = 'dt', col_types = 'T', skip = 1L)
Error in as.POSIXct.numeric(double()) : 'origin' must be supplied
Calls: <Anonymous> ... collector_value.collector_datetime -> as.POSIXct -> as.POSIXct.numeric
```
This commit fixes the error by using a character() vector instead of a double() vector.
> fix issue with empty date and datetime columns

- tests/testthat/test-vroom_write.R
Which now correctly distinguishes between NA and "NA"
Could you please also plan for a patch release in the next two weeks?
> Test fix for dev waldo

- NEWS.md
- R/cpp11.R
- src/cpp11.cpp
- src/vroom_write.cc
Fixes #510 
I don't think we should merge this yet, but I do think it should fix the issue.
Has something to do with the fact that `std::async` will force a copy of the arguments you pass it, even if they ultimately get called in `f` as `const reference`, because `std::async` has no way of knowing that.
So to perfect forward a const reference, the right way to do it is to wrap the thing you want a reference to in `std::ref()` and pass that along instead.
I am not entirely sure why this broke with new cpp11. Probably some cpp11 destructor is being run (on the thread?) that unprotects the underlying SEXP too early.
https://stackoverflow.com/questions/18359864/passing-arguments-to-stdasync-by-reference-fails
https://www.linkedin.com/pulse/careful-when-using-const-reference-stdthread-stdasync- …
> Speculative fix for vroom issue

- NEWS.md
- R/path.R
- tests/testthat/test-multi-file.R
Fixes #509 
This amends `standardise_path` to work with a list of connections, as referred to in the vignette.
The test for this functionality "vroom works with many connections" was incorrectly passing a character vector of paths to `vroom` instead of a list of connections, so this wasn't being picked up as a failing test.
> Allow reading list of connections

- src/cpp11.cpp
- src/vroom_write.cc
- cpp11.cpp: `<cstddef>` for `ptrdiff_t`
- vroom_write.cc: for `<functional>` `std::cref`
---
Our tooling also recommends directly including the following cpp11 headers to src/cpp11.cpp, but I omitted that as it feels more stylistic:
- `"cpp11/as.hpp"` for `as_cpp` and `as_sexp`
- `"cpp11/integers.hpp"` for `integers`
Happy to update the patch to include those if desired.
> Include missing headers

- .github/workflows/R-CMD-check.yaml
- NEWS.md
- src/r_utils.h
- src/unicode_fopen.h
- src/utils.h
- src/vroom_big_int.h
- src/vroom_chr.h
- src/vroom_date.h
- src/vroom_dbl.h
- src/vroom_dttm.h
- src/vroom_fct.h
- src/vroom_int.h
- src/vroom_num.h
- src/vroom_rle.h
- src/vroom_time.h
- src/vroom_write.cc
> Align argument types and format strings

- src/iconv_file.cc
cpp11 allows some somewhat scary implicit conversions between `sexp` and the 3 types `bool`, `size_t`, and `double`. These are unchecked conversions, and we'd like to remove them:
https://github.com/r-lib/cpp11/pull/390/
The recommended way is to use `cpp11::as_cpp<bool>()`, which checks the type and length before performing the conversion.
I'm not going to remove these in this version of cpp11, but we will in the next
> Avoid implicit conversion from `sexp` to `bool`
